Repository wiremod/wire, pull requests merged in 2019-05, with the labels that each got.

#1888 Enhanced UTF-8 functionality for E2 (fixes #1887)
  lua/entities/gmod_wire_expression2/core/string.lua
  lua/wire/client/e2descriptions.lua
Labels: Needs Testing, Needs work

#1918 add e:podStripWeapons()
  lua/entities/gmod_wire_expression2/core/entity.lua
  lua/wire/client/e2descriptions.lua
Labels: Needs Testing

#1933 Add e:weapons()
  lua/entities/gmod_wire_expression2/core/weapon.lua
  lua/wire/client/e2descriptions.lua
Labels: Solution/PR pending

#1869 Better outlines/line strips and vertices caching
  lua/entities/gmod_wire_egp/lib/egplib/usefulfunctions.lua
  lua/entities/gmod_wire_egp/lib/objects/circle.lua
  lua/entities/gmod_wire_egp/lib/objects/circleoutline.lua
  lua/entities/gmod_wire_egp/lib/objects/linestrip.lua
  lua/entities/gmod_wire_egp/lib/objects/poly.lua
  lua/entities/gmod_wire_egp/lib/objects/polyoutline.lua
  lua/entities/gmod_wire_egp/lib/objects/roundedbox.lua
  lua/entities/gmod_wire_egp/lib/objects/roundedboxoutline.lua
  lua/entities/gmod_wire_egp/lib/objects/wedge.lua
  lua/entities/gmod_wire_egp/lib/objects/wedgeoutline.lua
Labels: Solution/PR pending

#1542 Implement VTRANSFORM opcode
  lua/wire/zvm/zvm_opcodes.lua
Labels: Needs Testing, ZCPU
