Repository wiremod/wire, pull requests merged in 2019-04, with the labels that each got.

#1859 Fix digital screen
  lua/entities/gmod_wire_digitalscreen/cl_init.lua
  lua/entities/gmod_wire_digitalscreen/init.lua
Labels: Solution/PR pending

#1586 Refactor runOnWhatever to store clk var in e2 context
  lua/entities/gmod_wire_expression2/core/chat.lua
  lua/entities/gmod_wire_expression2/core/datasignal.lua
  lua/entities/gmod_wire_expression2/core/files.lua
  lua/entities/gmod_wire_expression2/core/gametick.lua
  lua/entities/gmod_wire_expression2/core/http.lua
  lua/entities/gmod_wire_expression2/core/player.lua
  lua/entities/gmod_wire_expression2/core/signal.lua
Labels: E2, Needs Testing

#1873 E2: Add wirelink:egpObjectIndexes() function (fixes #1865)
  lua/entities/gmod_wire_expression2/core/egpfunctions.lua
  lua/wire/client/e2descriptions.lua
Labels: Needs work

#1874 E2: Add wirelink:egpObjectType(n) & wirelink:egpObjectTypes() functions (fixes #1864)
  lua/entities/gmod_wire_expression2/core/egpfunctions.lua
  lua/wire/client/e2descriptions.lua
Labels: Needs work

#1893 Remove timed property from setMass and setColor
  lua/wire/gates/entity.lua
Labels: Needs Testing
