Repository wiremod/wire, pull requests merged in 2022-09, with the labels that each got.

#2392 Add warnings & attributes system
  lua/entities/gmod_wire_expression2/base/compiler.lua
  lua/entities/gmod_wire_expression2/cl_init.lua
  lua/entities/gmod_wire_expression2/core/array.lua
  lua/entities/gmod_wire_expression2/core/color.lua
  lua/entities/gmod_wire_expression2/core/constraint.lua
  lua/entities/gmod_wire_expression2/core/custom/prop.lua
  lua/entities/gmod_wire_expression2/core/extpp.lua
  lua/entities/gmod_wire_expression2/core/globalvars.lua
  lua/entities/gmod_wire_expression2/core/init.lua
  lua/entities/gmod_wire_expression2/core/wirelink.lua
  lua/wire/client/text_editor/wire_expression2_editor.lua
  lua/wire/stools/expression2.lua
Labels: Enhancement, E2, Text editor

#2400 Add unit tests for E2
  data/expression2/tests/parsing.txt
  data/expression2/tests/regressions/1975.txt
  data/expression2/tests/regressions/2388.txt
  data/expression2/tests/regressions/2403.txt
  data/expression2/tests/strict.txt
  lua/entities/gmod_wire_expression2/core/e2lib.lua
  lua/entities/gmod_wire_expression2/core/e2tests.lua
  lua/entities/gmod_wire_expression2/core/init.lua
  lua/entities/gmod_wire_expression2/init.lua
Labels: Enhancement, E2

#2394 new features
  lua/entities/gmod_wire_expression2/core/player.lua
  lua/entities/gmod_wire_friendslist.lua
  lua/entities/gmod_wire_ranger.lua
  lua/wire/stools/friendslist.lua
Labels: Enhancement

#2409 Prompt user when saving a new file in the E2 editor would overwrite an existing one
  lua/wire/client/cl_wirelib.lua
  lua/wire/client/text_editor/wire_expression2_editor.lua
Labels: Enhancement, E2, Text editor

#2406 Tokenizer Rewrite
  data/expression2/tests/parsing.txt
  lua/entities/gmod_wire_expression2/base/parser.lua
  lua/entities/gmod_wire_expression2/base/tokenizer.lua
  lua/entities/gmod_wire_expression2/core/e2lib.lua
Labels: Enhancement, E2

#2399 Switch vector and angle types to use userdata types
  lua/entities/gmod_wire_expression2/core/angle.lua
  lua/entities/gmod_wire_expression2/core/bone.lua
  lua/entities/gmod_wire_expression2/core/color.lua
  lua/entities/gmod_wire_expression2/core/compat.lua
  lua/entities/gmod_wire_expression2/core/custom/prop.lua
  lua/entities/gmod_wire_expression2/core/debug.lua
  lua/entities/gmod_wire_expression2/core/e2lib.lua
  lua/entities/gmod_wire_expression2/core/egpfunctions.lua
  lua/entities/gmod_wire_expression2/core/entity.lua
  lua/entities/gmod_wire_expression2/core/hologram.lua
  lua/entities/gmod_wire_expression2/core/matrix.lua
  lua/entities/gmod_wire_expression2/core/player.lua
  lua/entities/gmod_wire_expression2/core/quaternion.lua
  lua/entities/gmod_wire_expression2/core/ranger.lua
  lua/entities/gmod_wire_expression2/core/vector.lua
  lua/entities/gmod_wire_expression2/core/vector2.lua
  lua/entities/gmod_wire_expression2/core/wirelink.lua
Labels: Enhancement, E2
