Repository wiremod/wire, pull requests merged in 2022-11, with the labels that each got.

#2464 Add `noreturn` function attribute
  lua/entities/gmod_wire_expression2/base/compiler.lua
  lua/entities/gmod_wire_expression2/core/core.lua
  lua/entities/gmod_wire_expression2/core/extpp.lua
Labels: Enhancement, E2

#2467 Fix #2465
  lua/entities/gmod_wire_expression2/base/preprocessor.lua
Labels: E2

#2466 Add `effectCanPlay(void)` and `effectCanPlay(s)`
  lua/entities/gmod_wire_expression2/core/custom/effects.lua
  lua/wire/client/e2descriptions.lua
Labels: Enhancement, E2

#2457 Limit WireLib.TriggerInput to avoid stack overflow
  lua/wire/server/wirelib.lua
Labels: E2, Needs Testing

#2470 Add chat replacement function to E2
  lua/entities/gmod_wire_expression2/core/chat.lua
  lua/wire/client/e2descriptions.lua
Labels: Enhancement, E2

#2471 Add wire forcer hook
  lua/entities/gmod_wire_forcer.lua
Labels: Enhancement, Prop protection

#2488 E2 Fixes
  data/expression2/tests/regressions/2465.txt
  data/expression2/tests/regressions/2481.txt
  lua/entities/gmod_wire_expression2/base/compiler.lua
Labels: E2

#2452 Add `event`s to Expression 2
  data/expression2/tests/parsing.txt
  lua/entities/gmod_wire_expression2/base/compiler.lua
  lua/entities/gmod_wire_expression2/base/parser.lua
  lua/entities/gmod_wire_expression2/core/chat.lua
  lua/entities/gmod_wire_expression2/core/core.lua
  lua/entities/gmod_wire_expression2/core/e2lib.lua
  lua/entities/gmod_wire_expression2/core/extloader.lua
  lua/entities/gmod_wire_expression2/core/extpp.lua
  lua/entities/gmod_wire_expression2/core/files.lua
  lua/entities/gmod_wire_expression2/core/gametick.lua
  lua/entities/gmod_wire_expression2/core/http.lua
  lua/entities/gmod_wire_expression2/core/init.lua
  lua/entities/gmod_wire_expression2/core/player.lua
  lua/entities/gmod_wire_expression2/core/wirelink.lua
  lua/entities/gmod_wire_expression2/init.lua
  lua/wire/client/text_editor/modes/e2.lua
  lua/wire/client/text_editor/texteditor.lua
  lua/wire/client/text_editor/wire_expression2_editor.lua
  lua/wire/stools/expression2.lua
Labels: Enhancement, E2

#2497 Add variable and type autocomplete
  lua/wire/client/text_editor/modes/e2.lua
  lua/wire/client/text_editor/texteditor.lua
Labels: Enhancement, E2, Text editor

#2498 Easier to read text
  lua/wire/client/text_editor/texteditor.lua
Labels: Enhancement, E2, Text editor
