Repository wiremod/wire, pull requests merged in 2023-01, with the labels that each got.

#2500 E2 discard (`_`) parameters
  data/expression2/tests/parsing.txt
  lua/entities/gmod_wire_expression2/base/compiler.lua
  lua/entities/gmod_wire_expression2/base/parser.lua
  lua/entities/gmod_wire_expression2/base/tokenizer.lua
  lua/wire/client/text_editor/modes/e2.lua
Labels: Enhancement, E2

#2510 Remove FinishChat hook on Shutdown
  lua/entities/gmod_wire_expression2/core/cl_player.lua
Labels: Stale

#2501 Constraint Core code facelift
  lua/entities/gmod_wire_expression2/core/custom/constraintcore.lua
Labels: E2, Cleanup, Stale
